/*
 * This file was generated by the Gradle 'init' task.
 */

import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar
import com.github.jengelman.gradle.plugins.shadow.transformers.AppendingTransformer

plugins {
    application
    id("com.gradleup.shadow") version "9.4.0"
    id("checkstyle")
    id("jacoco")
}

group = "com.arifbanai"
version = "0.7.0-alpha-proxysupport-SNAPSHOT"
description = "JMusicBot"

// Workaround for Shadow plugin compatibility with newer Gradle versions
extra["mainClassName"] = "com.jagrosh.jmusicbot.JMusicBot"

repositories {
    mavenCentral()
    maven {
        url = uri("https://m2.dv8tion.net/releases")
    }
    maven {
        url = uri("https://jitpack.io")
    }
    maven {
        url = uri("https://maven.lavalink.dev/releases")
    }
    maven {
        url = uri("https://m2.chew.pro/releases")
    }
}

dependencies {
    // Discord Dependencies
    implementation(libs.net.dv8tion.jda)
    implementation(libs.pw.chew.jda.chewtils) {
        exclude(group = "org.slf4j", module = "slf4j-api")
        exclude(group = "org.jetbrains.kotlin", module = "kotlin-stdlib")
        exclude(group = "org.jetbrains.kotlin", module = "kotlin-stdlib-common")
        exclude(group = "com.squareup.okhttp3", module = "okhttp")
        exclude(group = "com.squareup.okio", module = "okio")
    }

    // DAVE Protocol Dependencies
    implementation(libs.club.minnced.jdave.api)
    implementation(libs.club.minnced.jdave.native.linux.x86.v64)
    implementation(libs.club.minnced.jdave.native.linux.aarch64)
    implementation(libs.club.minnced.jdave.native.win.x86.v64)
    implementation(libs.club.minnced.jdave.native.darwin)

    // Native Audio Send (udpqueue) Dependencies
    implementation(libs.club.minnced.udpqueue.native.linux.x86.v64)
    implementation(libs.club.minnced.udpqueue.native.linux.x86)
    implementation(libs.club.minnced.udpqueue.native.linux.aarch64)
    implementation(libs.club.minnced.udpqueue.native.linux.arm)
    implementation(libs.club.minnced.udpqueue.native.linux.musl.x86.v64)
    implementation(libs.club.minnced.udpqueue.native.linux.musl.aarch64)
    implementation(libs.club.minnced.udpqueue.native.win.x86.v64)
    implementation(libs.club.minnced.udpqueue.native.win.x86)
    implementation(libs.club.minnced.udpqueue.native.win.aarch64)
    implementation(libs.club.minnced.udpqueue.native.darwin)

    // Music Dependencies
    implementation(libs.com.github.arif.banai.lavaplayer)
    implementation(libs.com.github.arif.banai.youtube.source)

    // Misc Internal Dependencies
    implementation(libs.ch.qos.logback.logback.classic)
    implementation(libs.com.typesafe.config)
    implementation(libs.org.jsoup.jsoup)
    implementation(libs.com.fasterxml.jackson.core.jackson.databind)

    // GUI Dependencies
    implementation(libs.com.formdev.flatlaf)
    implementation(libs.com.formdev.flatlaf.extras)

    // Testing Dependencies
    testImplementation(platform(libs.org.junit.bom))
    testImplementation(libs.org.junit.jupiter.junit.jupiter)
    testImplementation(libs.org.mockito.mockito.core)
    testImplementation(libs.org.mockito.mockito.junit.jupiter)
    testImplementation(libs.org.hamcrest.hamcrest.core)
    testImplementation(libs.com.squareup.okhttp3.mockwebserver)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(25))
    }
}

application {
    mainClass.set("com.jagrosh.jmusicbot.JMusicBot")
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc> {
    options.encoding = "UTF-8"
}

// Configure Shadow JAR (Fat JAR)
tasks.shadowJar {
    archiveClassifier.set("All")
    mergeServiceFiles()
    append("reference.conf")
    transform(AppendingTransformer::class.java) {
        resource = "reference.conf"
    }
    manifest {
        attributes(
            "Main-Class" to "com.jagrosh.jmusicbot.JMusicBot",
            "Implementation-Title" to project.name,
            "Implementation-Version" to project.version
        )
    }
}

// Disable default distribution tasks to avoid duplicate file errors
tasks.distTar { enabled = false }
tasks.distZip { enabled = false }

// Make 'build' task depend on 'shadowJar'
tasks.build {
    dependsOn(tasks.shadowJar)
}

checkstyle {
    toolVersion = "10.12.0" // Use a recent version or match pom if specific
    configFile = file("google_checks.xml")
    isIgnoreFailures = false
    isShowViolations = true
}

// Only run checkstyle if the config file exists
tasks.withType<Checkstyle> {
    enabled = file("google_checks.xml").exists()
}

tasks.test {
    useJUnitPlatform()
}
