/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://m2.dv8tion.net/releases")
    }

    maven {
        url = uri("https://jitpack.io")
    }

    maven {
        url = uri("https://maven.lavalink.dev/releases")
    }

    maven {
        url = uri("https://m2.chew.pro/releases")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.net.dv8tion.jda)
    api(libs.pw.chew.jda.chewtils) {
        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.4.0/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "org.slf4j", "module" to "slf4j-api"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.4.0/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "org.jetbrains.kotlin", "module" to "kotlin-stdlib"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.4.0/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "org.jetbrains.kotlin", "module" to "kotlin-stdlib-common"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.4.0/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "com.squareup.okhttp3", "module" to "okhttp"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.4.0/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "com.squareup.okio", "module" to "okio"))
    }
    api(libs.club.minnced.jdave.api)
    api(libs.club.minnced.jdave.native.linux.x86.v64)
    api(libs.club.minnced.jdave.native.linux.aarch64)
    api(libs.club.minnced.jdave.native.win.x86.v64)
    api(libs.club.minnced.jdave.native.darwin)
    api(libs.club.minnced.udpqueue.native.linux.x86.v64)
    api(libs.club.minnced.udpqueue.native.linux.x86)
    api(libs.club.minnced.udpqueue.native.linux.aarch64)
    api(libs.club.minnced.udpqueue.native.linux.arm)
    api(libs.club.minnced.udpqueue.native.linux.musl.x86.v64)
    api(libs.club.minnced.udpqueue.native.linux.musl.aarch64)
    api(libs.club.minnced.udpqueue.native.win.x86.v64)
    api(libs.club.minnced.udpqueue.native.win.x86)
    api(libs.club.minnced.udpqueue.native.win.aarch64)
    api(libs.club.minnced.udpqueue.native.darwin)
    api(libs.com.github.arif.banai.lavaplayer)
    api(libs.com.github.arif.banai.youtube.source)
    api(libs.ch.qos.logback.logback.classic)
    api(libs.com.typesafe.config)
    api(libs.org.jsoup.jsoup)
    api(libs.com.fasterxml.jackson.core.jackson.databind)
    api(libs.com.formdev.flatlaf)
    api(libs.com.formdev.flatlaf.extras)
    testImplementation(libs.org.junit.jupiter.junit.jupiter)
    testImplementation(libs.org.mockito.mockito.core)
    testImplementation(libs.org.mockito.mockito.junit.jupiter)
    testImplementation(libs.org.hamcrest.hamcrest.core)
    testImplementation(libs.com.squareup.okhttp3.mockwebserver)
}

group = "com.arifbanai"
version = "0.7.0-alpha-proxysupport-SNAPSHOT"
description = "JMusicBot"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
